from markdown_pdf import MarkdownPdf, Section

class Report:

    """
    This class is responsible for building the EEG report in PDF format.
    """

    def __init__(self, eeg):
        self.eeg = eeg

    def add_data_pdf(self, content: list[str], toc: bool = True, center: bool = False) -> None:

        """
        Adds the content to the pdf
        
        Parameters
        ----------
        content : list
            The content to add to the pdf
        toc : bool
            Whether to add a table of contents
        center : bool
            Whether to center the content

        Returns (External)
        ------------------ 
        Report: PDF
            A section of the SOMA report
        """

        #Formatting
        user_css = 'h4 {text-align:center;}' if center else None
        section = Section(' \n '.join(content), toc=toc)
        self.pdf.add_section(section, user_css=user_css)

    def build_report(self):
        self.pdf = MarkdownPdf(toc_level=3)

        section_text = ['# EEG Report',
                        'This report was generated by quickeeg']
        self.add_data_pdf(section_text)

        